name: Wait for a Minute

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited]

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for a minute
        run: sleep 60
