name: Wait for Five Minutes

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited]

  repository_dispatch:
    types: [wait-for-five-minutes]

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for five minutes
        run: sleep 300 
