name: Wait for x minutes
run-name: Wait for ${{ github.event.inputs.minutes }} minute(s)

on:
  workflow_dispatch:
    inputs:
      minutes:
        description: 'Number of minutes to wait. Note: integers only'
        required: true
        type: number
        default: 5

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: wait for specified minutes
        run: sleep $(( ${{ github.event.inputs.minutes }} * 60 ))
