name: Wait a minute then fail

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for a minute
        run: sleep 60
      - name: Fail the job
        run: exit 1
